-- =====================================================
-- TABLA: producto
-- =====================================================
INSERT INTO producto (id, enlace, nombre, precio, precioAnterior, descuento, calificacion, imagen, insignia, descripcion, descripcionCorta, disponibilidad, categoriaId, activo, fechaCreacion, fechaActualizacion) VALUES
(1, 'saltena-de-pollo',         'Salteña de Pollo',         12.00, 15.00, '20% OFF', '4.9', '/img/06_Productos/saltena-pollo.jpg',         'Más vendida', 'Salteña jugosa de pollo con la receta tradicional cruceña: masa dorada, caldo de pollo y picante a elección.', 'La clásica de pollo, jugosa y dorada.',            'En stock', 1, 1, NOW(), NOW()),
(2, 'saltena-de-carne',         'Salteña de Carne',         13.00, NULL,  NULL,      '4.8', '/img/06_Productos/saltena-carne.jpg',         NULL,           'Salteña de carne de res desmechada con verduras y el toque secreto de la casa.',                     'Carne de res jugosa con el toque de la casa.',    'En stock', 1, 1, NOW(), NOW()),
(3, 'saltena-de-pollo-picante', 'Salteña de Pollo Picante', 12.50, NULL,  NULL,      '4.9', '/img/06_Productos/saltena-pollo-picante.jpg', 'Picante',      'Para los que aman el picante: pollo con ají y especias extra.',                                       'Pollo con picante intenso.',                       'En stock', 1, 1, NOW(), NOW()),
(4, 'saltena-vegetariana',      'Salteña Vegetariana',      11.00, NULL,  NULL,      '4.7', '/img/06_Productos/saltena-vegetariana.jpg',   NULL,           'Salteña rellena de verduras frescas, queso y sin carne.',                                              'Verduras y queso, sin carne.',                     'En stock', 2, 1, NOW(), NOW()),
(5, 'jugo-de-mango',            'Jugo Natural de Mango',    10.00, NULL,  NULL,      '4.8', '/img/06_Productos/jugo-mango.jpg',            NULL,           'Jugo natural de mango 100% fruta.',                                                                     'Refrescante jugo de mango.',                       'En stock', 3, 1, NOW(), NOW()),
(6, 'cafe-de-la-casa',          'Café de la Casa',           8.00, NULL,  NULL,      '4.6', '/img/06_Productos/cafe-casa.jpg',             NULL,           'Café recién preparado, ideal para acompañar tu salteña.',                                               'Café fresco para acompañar.',                      'En stock', 3, 1, NOW(), NOW());
